### ISSUE TITLE
Partial package.xml always comes out empty

### ISSUE THREAD

**Issue by ricka** [scolladon/sfdc-ci-toolkit#18]
We are trying to use this tool with `npm run partial-package` but getting empty `package.xml` files with every invocation. Seems like a bug, but I'm uncertain from the documentation if we are missing something.

Is running `npm run profile-completion` and `npm run profile-reconciliation` a requirement for the partial package build? Is this method up to date?

**Comment by scolladon** [comment]
Hello, the partial package command should be applied on the metadata and it should take two commit references. Look at the file https://github.com/scolladon/sfdc-ci-toolkit/blob/master/gulp-tasks/prepare-package.js for the requirements

**Comment by ricka** [comment]
After recloning and reconfiguring, I'm unsure what this issue was as everything is running.
